# Generated by Django 5.1.1 on 2024-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trader', '0002_rename_stock_portfoliostock_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
