# Generated by Django 5.1.1 on 2024-09-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trader', '0003_transaction_portfoliostock_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
