# Generated by Django 5.1.1 on 2024-09-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trader', '0006_alter_portfoliostock_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostock',
            name='name',
            field=models.CharField(default='Apple Inc', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='symbol',
            field=models.CharField(default='AAPL', max_length=5),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='Apple Inc', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(default='AAPL', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='buy', max_length=4),
        ),
    ]
